# Generated by Django 5.0.6 on 2024-07-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Sinif kodu')),
            ],
            options={
                'verbose_name': 'Sinif kodu',
                'verbose_name_plural': 'Sinif kodu',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İmtahan')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qiymət')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə tarixi')),
            ],
            options={
                'verbose_name': 'İmtahan',
                'verbose_name_plural': 'İmtahan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Qrup')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qiymət')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə tarixi')),
            ],
            options={
                'verbose_name': 'Qrup',
                'verbose_name_plural': 'Qrup',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vəzifə')),
            ],
            options={
                'verbose_name': 'Vəzifə',
                'verbose_name_plural': 'Vəzifə',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Proximity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yaxınlığı')),
            ],
            options={
                'verbose_name': 'Yaxınlığı',
                'verbose_name_plural': 'Yaxınlığı',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sinif')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qiymət')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə tarixi')),
            ],
            options={
                'verbose_name': 'Sinif',
                'verbose_name_plural': 'Sinif',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fənn')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qiymət')),
            ],
            options={
                'verbose_name': 'Fənn',
                'verbose_name_plural': 'Fənn',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='Tədris ili')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə tarixi')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tədris ili',
                'verbose_name_plural': 'Tədris ili',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.IntegerField(unique=True, verbose_name='İş nömrəsi')),
                ('registration_status', models.CharField(choices=[('Registered', 'Qeydiyyatdadır'), ('Out', 'Çıxıb')], default='Registered', max_length=14, verbose_name='Qeydiyyat statusu')),
                ('registration_type', models.CharField(choices=[('New', 'Yeni qeydiyyat'), ('Again', 'Təkrar qeydiyyat')], default='New', max_length=16, verbose_name='Qeydiyyat növü')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('gender', models.CharField(choices=[('Man', 'Kişi'), ('Woman', 'Qadın')], default='Man', max_length=16, verbose_name='Cinsiyyət')),
                ('shift', models.CharField(choices=[('Morning', 'Səhər'), ('Afternoon', 'Günorta')], default='Morning', max_length=10, verbose_name='Növbə')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Qeydiyyat')),
                ('section', models.CharField(choices=[('Azerbaijan', 'Azərbaycan'), ('Russian', 'Rus')], max_length=10, verbose_name='Bölmə')),
                ('score', models.IntegerField(verbose_name='Qəbul balı')),
                ('school', models.CharField(max_length=100, verbose_name='Məktəb')),
                ('city', models.CharField(max_length=100, verbose_name='Şəhər')),
                ('address', models.CharField(max_length=250, verbose_name='Ünvan')),
                ('concession_1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Güzəşt-1 adı')),
                ('concession_1_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Güzəşt-1 məbləği')),
                ('concession_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Güzəşt-2 adı')),
                ('concession_2_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Güzəşt-2 məbləği')),
                ('concession_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Güzəşt-3 adı')),
                ('concession_3_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Güzəşt-3 məbləği')),
                ('concession_1_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Güzəşt-1 faiz')),
                ('concession_2_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Güzəşt-2 faiz')),
                ('concession_3_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Güzəşt-3 faiz')),
                ('total_concession', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Cəmi güzəşt məbləği')),
                ('father_first_name', models.CharField(max_length=100, verbose_name='Ata adı')),
                ('father_last_name', models.CharField(max_length=100, verbose_name='Ata soyad')),
                ('father_workplace', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ata iş yeri')),
                ('father_phone_1', models.CharField(max_length=15, verbose_name='Ata telefon 1')),
                ('father_phone_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ata telefon 2')),
                ('mather_first_name', models.CharField(max_length=100, verbose_name='Ana ad')),
                ('mather_last_name', models.CharField(max_length=100, verbose_name='Ana soyad')),
                ('mather_workplace', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ana iş yeri')),
                ('mather_phone_1', models.CharField(max_length=15, verbose_name='Ana telefon 1')),
                ('mather_phone_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ana telefon 2')),
                ('responsible_first_name', models.CharField(max_length=100, verbose_name='Məhsul şəxs adı')),
                ('responsible_last_name', models.CharField(max_length=100, verbose_name='Məhsul şəxs soyad')),
                ('responsible_sur_name', models.CharField(max_length=100, verbose_name='Məhsul şəxs ata adı')),
                ('responsible_passport_number', models.CharField(max_length=100, verbose_name='Məhsul şəxs vəsiqə nömrəsi')),
                ('responsible_fin', models.CharField(max_length=100, verbose_name='Məhsul şəxs vəsiqə FİN')),
                ('responsible_workplace', models.CharField(blank=True, max_length=100, null=True, verbose_name='Məhsul şəxs iş yeri')),
                ('responsible_address', models.CharField(max_length=250, verbose_name='Məhsul şəxs ünvan')),
                ('responsible_phone_1', models.CharField(max_length=15, verbose_name='Məsul şəxs telefon 1')),
                ('responsible_phone_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Məsul şəxs telefon 2')),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Təhsil haqqı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qeydiyyat tarixi')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Yenilənə tarixi')),
                ('is_split_edited', models.BooleanField(default=False)),
                ('is_debtor', models.BooleanField(default=False, verbose_name='Borc')),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_number', to='student.classnumber', verbose_name='Sinif kodu')),
                ('exam', models.ManyToManyField(related_name='exam', to='student.exam', verbose_name='İmtahan')),
                ('father_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_position', to='student.position', verbose_name='Vəzifə')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_student', to='student.group', verbose_name='Qrup')),
                ('mather_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mather_position', to='student.position', verbose_name='Vəzifə')),
                ('proximity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximity', to='student.proximity', verbose_name='Yaxınlığı')),
                ('responsible_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_position', to='student.position', verbose_name='Məhsul şəxs vəzifə')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_student', to='student.studentclass', verbose_name='Sinif')),
                ('subject', models.ManyToManyField(related_name='subject', to='student.subject', verbose_name='Fənn')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.year', verbose_name='Tədris ili')),
            ],
            options={
                'verbose_name': 'Şagird',
                'verbose_name_plural': 'Şagird',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('number_of_months', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='TuitionFeeSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_date', models.DateField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'ordering': ['installment_date'],
            },
        ),
    ]
